channels:
- conda-forge
- anaconda
dependencies:
- python=3.9.7
- pip:
  - adal==1.2.7
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.11.16
  - aiosignal==1.3.2
  - annotated-types==0.7.0
  - anyio==4.9.0
  - applicationinsights==0.11.10
  - arch==5.6.0
  - argcomplete==3.6.2
  - asttokens==3.0.0
  - async-timeout==5.0.1
  - attrs==25.3.0
  - azure-common==1.1.28
  - azure-core==1.33.0
  - azure-graphrbac==0.61.2
  - azure-identity==1.21.0
  - azure-mgmt-authorization==4.0.0
  - azure-mgmt-containerregistry==10.3.0
  - azure-mgmt-core==1.5.0
  - azure-mgmt-keyvault==10.3.1
  - azure-mgmt-network==28.1.0
  - azure-mgmt-resource==23.3.0
  - azure-mgmt-storage==22.1.1
  - azure-storage-blob==12.19.0
  - azure-storage-queue==12.12.0
  - azureml-automl-core==1.60.0
  - azureml-automl-dnn-vision==1.60.0
  - azureml-automl-runtime==1.60.0
  - azureml-core==1.60.0
  - azureml-dataprep==5.1.6
  - azureml-dataprep-native==41.0.0
  - azureml-dataprep-rslex==2.22.5
  - azureml-dataset-runtime==1.60.0
  - azureml-defaults==1.60.0
  - azureml-inference-server-http==1.4.0
  - azureml-interpret==1.60.0
  - azureml-mlflow==1.60.0
  - azureml-responsibleai==1.60.0
  - azureml-telemetry==1.60.0
  - azureml-train-automl-client==1.60.0
  - azureml-train-automl-runtime==1.60.0
  - azureml-train-core==1.60.0
  - azureml-train-restclients-hyperdrive==1.60.0
  - azureml-training-tabular==1.60.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.3.0
  - blinker==1.9.0
  - bokeh==2.4.3
  - cachetools==5.5.2
  - captum==0.5.0
  - colorcet==3.0.1
  - coloredlogs==15.0.1
  - comm==0.2.2
  - contextlib2==21.6.0
  - cryptography==44.0.2
  - dask==2023.2.0
  - databricks-sdk==0.50.0
  - dataclasses==0.6
  - debugpy==1.8.14
  - decorator==5.2.1
  - deprecated==1.2.18
  - dice-ml==0.11
  - dill==0.3.9
  - distributed==2023.2.0
  - distro==1.9.0
  - docker==7.1.0
  - dotnetcore2==3.1.23
  - econml==0.15.1
  - erroranalysis==0.5.5
  - exceptiongroup==1.2.2
  - executing==2.2.0
  - fairlearn==0.7.0
  - fastapi==0.115.12
  - filelock==3.18.0
  - fire==0.7.0
  - flask==3.0.3
  - flask-cors==5.0.1
  - flatbuffers==25.2.10
  - frozenlist==1.5.0
  - fsspec==2025.3.2
  - fusepy==3.0.1
  - fvcore==0.1.5.post20221221
  - gensim==4.3.2
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-api-core==2.24.2
  - google-auth==2.38.0
  - googleapis-common-protos==1.70.0
  - gunicorn==23.0.0
  - h11==0.14.0
  - humanfriendly==10.0
  - imageio==2.37.0
  - importlib-metadata==8.2.0
  - importlib-resources==6.4.0
  - inference-schema==1.8
  - interpret-community==0.31.0
  - interpret-core==0.5.0
  - iopath==0.1.10
  - ipykernel==6.29.5
  - ipython==8.18.1
  - isodate==0.7.2
  - itsdangerous==2.2.0
  - jedi==0.19.2
  - jeepney==0.9.0
  - jinja2==3.1.6
  - jmespath==0.10.0
  - jsonpickle==4.0.5
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - jupyter-client==8.6.3
  - jupyter-core==5.7.2
  - keras2onnx==1.6.0
  - knack==0.12.0
  - lightgbm==4.6.0
  - locket==1.0.0
  - markupsafe==3.0.2
  - matplotlib==3.6.3
  - matplotlib-inline==0.1.7
  - ml-wrappers==0.5.6
  - mlflow-skinny==2.21.3
  - mpmath==1.3.0
  - msal==1.32.0
  - msal-extensions==1.3.1
  - msgpack==1.1.0
  - msrest==0.7.1
  - msrestazure==0.6.4.post1
  - multidict==6.4.3
  - munch==4.0.0
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.6.0
  - networkx==2.5
  - nose==1.3.7
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==8.9.2.26
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-nccl-cu12==2.19.3
  - nvidia-nvjitlink-cu12==12.8.93
  - nvidia-nvtx-cu12==12.1.105
  - oauthlib==3.2.2
  - onnx==1.17.0
  - onnxconverter-common==1.13.0
  - onnxmltools==1.12.0
  - onnxruntime==1.17.3
  - opencensus==0.11.4
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.14
  - opencv-python-headless==4.8.1.78
  - opentelemetry-api==1.32.0
  - opentelemetry-sdk==1.32.0
  - opentelemetry-semantic-conventions==0.53b0
  - param==2.2.0
  - paramiko==3.5.1
  - parso==0.8.4
  - partd==1.4.2
  - pathspec==0.12.1
  - patsy==1.0.1
  - pexpect==4.9.0
  - pkginfo==1.12.1.2
  - pmdarima==1.8.5
  - portalocker==3.1.1
  - pretrainedmodels==0.7.4
  - prompt-toolkit==3.0.50
  - propcache==0.3.1
  - property-cached==1.6.4
  - proto-plus==1.26.1
  - protobuf==5.29.4
  - ptyprocess==0.7.0
  - pure-eval==0.2.3
  - pyarrow==14.0.2
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pyct==0.5.0
  - pydantic==2.9.2
  - pydantic-core==2.23.4
  - pydantic-settings==2.8.1
  - pygments==2.19.1
  - pyjwt==2.10.1
  - pynacl==1.5.0
  - pynvml==8.0.4
  - pyopenssl==25.0.0
  - python-dotenv==1.1.0
  - pytorch-ignite==0.4.13
  - pywavelets==1.6.0
  - pyyaml==6.0.2
  - pyzmq==26.4.0
  - raiutils==0.4.2
  - recordclass==0.21.1
  - referencing==0.36.2
  - requests-oauthlib==2.0.0
  - resnest==0.0.6b20210504
  - responsibleai==0.36.0
  - rpds-py==0.24.0
  - rsa==4.9
  - s3transfer==0.5.2
  - saliency==0.1.3
  - scikit-image==0.19.3
  - secretstorage==3.3.3
  - semver==2.13.0
  - simplification==0.7.12
  - skl2onnx==1.15.0
  - sklearn-pandas==1.7.0
  - smart-open==6.4.0
  - smmap==5.0.2
  - sniffio==1.3.1
  - sortedcontainers==2.4.0
  - sparse==0.15.5
  - sqlparse==0.5.3
  - stack-data==0.6.3
  - starlette==0.46.2
  - statsmodels==0.13.5
  - sympy==1.13.3
  - tabulate==0.9.0
  - tblib==3.1.0
  - termcolor==3.0.1
  - tifffile==2024.8.30
  - timm==0.4.12
  - toolz==1.0.0
  - torch==2.2.2
  - torchvision==0.17.2
  - tornado==6.4.2
  - traitlets==5.14.3
  - triton==2.2.0
  - typing-extensions==4.13.2
  - urllib3==1.26.20
  - uvicorn==0.34.1
  - wcwidth==0.2.13
  - werkzeug==3.1.3
  - wrapt==1.16.0
  - yacs==0.1.8
  - yarl==1.19.0
  - zict==3.0.0
- boto3=1.20.19
- botocore=1.23.19
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- ca-certificates=2025.1.31
- certifi=2025.1.31
- cffi=1.14.6
- charset-normalizer=3.4.1
- cloudpickle=2.2.1
- colorama=0.4.6
- contourpy=1.3.0
- cycler=0.12.1
- cython=3.0.12
- fonttools=4.57.0
- freetype=2.12.1
- h2=4.2.0
- hpack=4.1.0
- hyperframe=6.1.0
- idna=3.10
- joblib=1.2.0
- kiwisolver=1.4.7
- lcms2=2.16
- lerc=4.0.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libdeflate=1.20
- libffi=3.3
- libgcc=14.2.0
- libgfortran=14.2.0
- libgfortran-ng=14.2.0
- libgfortran5=14.2.0
- libjpeg-turbo=3.0.0
- libllvm11=11.1.0
- liblzma=5.8.1
- liblzma-devel=5.8.1
- libopenblas=0.3.25
- libpng=1.6.43
- libsqlite=3.46.0
- libstdcxx=14.2.0
- libtiff=4.6.0
- libwebp-base=1.5.0
- libxcb=1.15
- libzlib=1.2.13
- llvmlite=0.39.1
- munkres=1.1.4
- numba=0.56.4
- numpy=1.23.5
- openjpeg=2.5.2
- packaging=24.2
- pandas=1.5.3
- pillow=10.3.0
- pip=21.3.1
- platformdirs=4.3.7
- pooch=1.8.2
- psutil=5.8.0
- pthread-stubs=0.4
- pycocotools=2.0.6
- pycparser=2.22
- pyparsing=3.2.3
- pysocks=1.7.1
- python-dateutil=2.9.0.post0
- python-tzdata=2025.2
- python_abi=3.9
- pytz=2025.2
- qhull=2020.2
- requests=2.32.3
- scikit-learn=1.5.1
- scipy=1.10.1
- setuptools=72.1.0
- six=1.17.0
- slicer=0.0.7
- tbb=2021.1.1
- threadpoolctl=3.6.0
- tqdm=4.67.1
- tzdata=2025b
- unicodedata2=16.0.0
- wheel=0.44.0
- xorg-libxau=1.0.12
- xorg-libxdmcp=1.1.5
- xz-gpl-tools=5.8.1
- xz-tools=5.8.1
- zipp=3.21.0
- zstandard=0.23.0
- zstd=1.5.6
name: project_environment
