$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: facade-defect-detection
display_name: Facade Defect Detection
description: Pipeline job for detecting defects in facade images using the parallel component

# Pipeline job inputs
inputs:
  batch_id:
    type: string
  input_dataset:
    type: uri_folder
  model:
    type: mlflow_model

# Pipeline job outputs
outputs:
  job_output:
    type: uri_folder

# Pipeline jobs using the component
jobs:
  facade_inference:
    type: command
    component: ./component.yml
    compute: azureml:cpu-cluster2
    resources:
      instance_count: 1
    inputs:
      input_ds: ${{parent.inputs.input_dataset}}
      batch_id: ${{parent.inputs.batch_id}}
      model1: ${{parent.inputs.model}}
      window_size: 512
      overlap: 64
      confidence: 50
      mode: "auto"
      local: False
    outputs:
      output_data: ${{parent.outputs.job_output}}

# Settings
settings:
  default_compute: azureml:cpu-cluster2