name: facadeai_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pip:
    # Core dependencies
    - mlflow>=2.2.0
    - opencv-python-headless==4.8.1.78
    - pillow>=9.4.0
    - numpy>=1.18.5,<=1.23.5
    - pandas>=1.5.3
    
    # Azure dependencies (minimal set for local development)
    - azure-cosmos>=4.3.0
    - azure-identity>=1.12.0
    - azure-keyvault-secrets>=4.6.0
    
    # Additional utilities
    - scikit-learn>=1.1.3
    - scikit-image>=0.19.3
    - matplotlib<=3.6.3
    - pyyaml
    - psutil