name: facade_ai_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pip:
    # Azure ML dependencies
    - azure-ai-ml==1.9.0
    - azureml-core>=1.48.0
    - azureml-dataset-runtime>=1.48.0
    - azureml-defaults>=1.48.0
    - azureml-mlflow>=1.48.0
    - azureml-telemetry>=1.48.0
    - azureml-automl-core>=1.48.0
    
    # Azure identity and storage
    - azure-identity>=1.12.0
    - azure-keyvault-secrets>=4.6.0
    - azure-cosmos>=4.3.0
    - azure-storage-blob>=12.14.0
    - azureml-automl-dnn-vision==1.60.0
    - azureml-automl-runtime==1.60.0
    # ML and data processing libraries
    - mlflow>=2.2.0
    - opencv-python-headless>=4.7.0  # Using headless version to avoid display dependencies
    - pillow>=9.4.0
    - numpy>=1.18.5,<=1.23.5
    - pandas>=1.5.3
    - matplotlib<=3.6.3  # Limited to 3.6.3 due to compatibility with azureml packages
    - scikit-image>=0.19.3
    - scikit-learn>=1.1.3
    
    # Utils
    - pyyaml
    - psutil
    - pyyaml
    # Utils
    - pyyaml
